version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    image: tutorial-mysql-buffering
    volumes:
      - ./app:/root/app
      - ./.env:/root/.env:ro
    depends_on:
        - db
    env_file:
      - ./.env

  db:
    image: postgres:13-buster
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local